version: '3'
services:
  # db:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: MYSQL_DATABASE
  #     MYSQL_USER: MYSQL_USER
  #     MYSQL_PASSWORD: MYSQL_PASSWORD
  #     MYSQL_ALLOW_EMPTY_PASSWORD: MYSQL_ALLOW_EMPTY_PASSWORD
  #   volumes:
  #     - "./db:/docker-entrypoint-initdb.d"
  #   networks:
  #     - LAMP

  php:
    # depends_on:
    #   - db
    image: php:8.1.1-apache
    volumes:
      - "./php/www:/var/www/html"
    ports:
      - 80:80
      # - 443:443
    networks:
      - LAMP
    # command: "/bin/sh -c 'docker-php-ext-install mysqli && exec apache2-foreground'"


  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 8001:80
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_PORT=PMA_PORT
  #   networks:
  #     - LAMP


networks:
  LAMP:
    driver: bridge
